apply plugin: 'com.android.library'

def VERSION_NAME = "1.2.1"
def VERSION_CODE = 102001

def ANDROID_COMPILE_SDK_VERSION = 34
def ANDROID_TARGET_SDK_VERSION = 34
//def ANDROID_BUILD_TOOLS_VERSION = project.ANDROID_BUILD_TOOLS_VERSION
def ANDROID_MIN_SDK_VERSION = 24

def JAVA_COMPATIBILITY =  JavaVersion.VERSION_17

android {
    namespace 'com.ngochai84.filechooser'
    compileSdkVersion ANDROID_COMPILE_SDK_VERSION
    //buildToolsVersion ANDROID_BUILD_TOOLS_VERSION
    resourcePrefix "obsez_fc__"

    defaultConfig {
        minSdkVersion ANDROID_MIN_SDK_VERSION
        targetSdkVersion ANDROID_TARGET_SDK_VERSION
    }
    buildTypes {
        release {
            minifyEnabled false
        }
//        debug {
//            buildConfig "public final static boolean HAS_PROTOTYPE_FEATURE = true;"
//        }
//        release {
//            buildConfig "public final static boolean HAS_PROTOTYPE_FEATURE = false;"
//        }
    }

    compileOptions {
        sourceCompatibility JAVA_COMPATIBILITY
        targetCompatibility JAVA_COMPATIBILITY
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
        disable 'InvalidPackage', 'OldTargetApi', 'IconDensities', 'deprecation'
        ignoreWarnings true
        lintConfig file('lint.xml')
        quiet true
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
}
